### ISSUE TITLE
Missing levinson when modelorder=1

### ISSUE THREAD

**Issue by WojciechMigda** [JuliaDSP/MFCC.jl#1]
When I run MFCC like this:
`mfcc(sig, MP3PARAMS.rate / float(DOWN_RATIO), modelorder=1)`

an error is reported:
`ERROR: levinson not defined`
`in dolpc at ${HOME}\.julia\v0.3\MFCC\src\rasta.jl:174`
`in mfcc at ${HOME}\.julia\v0.3\MFCC\src\mfccs.jl:29`

My `Pkg.status()`:
`8 required packages:`
`- DataFrames                    0.6.9`
`- HDF5                          0.5.5`
`- IJulia                        1.0.3`
`- MFCC                          0.0.2`
`- PyPlot                        2.1.0`
`- SPTK                          0.0.1`
`- WORLD                         0.1.3`
`- WinRPM                        0.1.12`

When `modelorder=0` it runs fine.

**Comment by davidavdav** [comment]
Thanks, this is a bug, `levinson()` is not defined.  I don't know _what_ I was doing...

**Comment by davidavdav** [comment]
Ah.  This is a result of moving stuff from a finer-grained module structure to a more coarse-grained. 

https://github.com/davidavdav/SignalProcessing.jl/blob/master/src/SignalProcessing.jl contains levinson it seems.  I remember figuring out the license terms with Paul Kienzle, and told the DSP people about it, but I suppose they never picked that up.

**Comment by davidavdav** [comment]
I thinks this has been resolved by now.
