### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by jfsantos** [JuliaDSP/MFCC.jl#17]
The current version of this package, which works with Julia 1.0 and 1.1, is currently not tagged or registered, so it's not possible to install it via Pkg.

**Comment by davidavdav** [comment]
OK, I've tried to find a way to register a new version to the new julia 1.1 registry for about half an hour now, and I can't find anything on the subject, so I give up for now.  

If you have a pointer to some docs that would be greatly appreciated.

**Comment by davidavdav** [comment]
OK, I got this message https://github.com/JuliaLang/METADATA.jl/pull/22770 , and I have no idea how to continue from here.  I cannot find any documentation on how to use Registrator, I can't even install the Julia package Registrator (is it a Julia package, or is it some Github thingamy?). 

Maybe someone from JuliaDSP can release this version?

**Comment by martinholters** [comment]
https://juliaregistrator.github.io/

**Comment by giordano** [comment]
> juliaregistrator.github.io

Installing it requires having admin rights.  I don't have them in https://github.com/JuliaDSP/Deconvolution.jl, for one.  I've sent a request to get it installed for that repo, but having it installed for all repositories would probably be more useful

**Comment by martinholters** [comment]
Agree and I don't have admin rights as well.

**Comment by davidavdav** [comment]
Thanks, it was not clear to me from the README / documentation that these were github operations.  I'll try again.

**Comment by davidavdav** [comment]
I have just released v0.3.3, this may resolve your issues.

**Comment by davidavdav** [comment]
Now v0.3.4
