### ISSUE TITLE
Fix deprecated usage of functions in feacalc

### ISSUE THREAD

**Issue by wheeheee** [JuliaDSP/MFCC.jl#34]
Right now `feacalc` throws an error, which I traced to 

- 2 instances of `sum` omitting the dims keyword argument
- one is in `sad`, the other is basically a copy of it, maybe `sad` can be called instead?
- Plus the `log10` looks like it is supposed to be broadcasted
- `Float64` should replace `float64`
- Indexing in `sad` looks old and doesn't work now but I still get BoundsErrors even after updating that.
- The `readall` in `soxread` should also be changed, and maybe also use an open do block?

**Comment by davidavdav** [comment]
Yes it looks like this code hasn't been used in many versions of Julia, incl version 1. 

Since you already put some effort in this, any chance you can fix this and submit a PR?

**Comment by davidavdav** [comment]
Yes, thanks!
